# Generated by Django 4.2.7 on 2025-07-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_city_user_countery_user_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
